### ISSUE TITLE
Unable to push to repo

### ISSUE THREAD

**Issue by evansavage** [DDMAL/xml-parse-glyph-img#3]
I enabled two-factor authentication successfully, though I cannot push to the repo at the new url. Error received is:

remote: Permission to DDMAL/xml-parse-glyph-img.git denied to evansavage.
fatal: unable to access 'https://github.com/DDMAL/xml-parse-glyph-img.git/': The requested URL returned error: 403

**Comment by vigliensoni** [comment]
I was able to push without problems. Did you clone the repo from the new organization?

**Comment by evansavage** [comment]
I created a new local repo to clone from the new DDMAL repository, and I received the same error while trying to push: both from the terminal and Atom's git client.
