### ISSUE TITLE
Manually clean the dataset

### ISSUE THREAD

**Issue by evansavage** [DDMAL/xml-parse-glyph-img#7]
The image processed erosion approach is not bullet-proof, and some files will need to be removed from the dataset manually as some text and neume segments do not parse correctly.

**Comment by vigliensoni** [comment]
Do you have an estimate of the percentage of glyphs where this process fails?

Could you upload some images in order to see the errors?

**Comment by evansavage** [comment]
For CF-010 from the Salzinnes folder, it grabbed 5 of 371 glyphs incorrectly. That's a 1.35% error.

**Comment by vigliensoni** [comment]
Could you paste here a screenshot of the errors?

**Comment by evansavage** [comment]
![CF_12_5_14](https://user-images.githubusercontent.com/23425011/58641263-dcbdb100-82c8-11e9-9c2a-3e5f10a9c731.png)

Occasionally, pieces of lyrics outside the staff will register as being a neume in my heuristic bounding box parsing process.

**Comment by evansavage** [comment]
Errors are much less present in the new Interactive Classifier data extraction approach.
