### ISSUE TITLE
Design a way to extract clef components correctly

### ISSUE THREAD

**Issue by evansavage** [DDMAL/xml-parse-glyph-img#8]
Some clefs have the separate blot to their left, which is recognized as a separate neume every time in the current process. A heuristic approach could be used by seeing if there is any overlap in the "second-most-left" neumes (contours in the context of opencv). If so, the neume to the left would belong to the clef, and coordinates could be updated as a function of both of their bounding boxes.

**Comment by vigliensoni** [comment]
The separate blot indicates this is an F clef. It could be beneficial to check if this heuristic approach is also useful in other manuscripts.

**Comment by evansavage** [comment]
In the Interactive Classifier, the separate blots that end up forming a clef can be easily joined together, though it would be nice to have an automatic process that would catch clefs on the way into using the classifier.
