### ISSUE TITLE
Handle neumes on top/bottom/outside of staff

### ISSUE THREAD

**Issue by evansavage** [DDMAL/xml-parse-glyph-img#9]
In the Salzinnes notation style, the extent to with which neumes extend outside of their relative stave is just above or below the topmost or bottommost staff lines respectively.

**Comment by vigliensoni** [comment]
Could you provide some examples of neumes outside of staff?

**Comment by evansavage** [comment]
![CF_10_0_25](https://user-images.githubusercontent.com/23425011/58641045-691ba400-82c8-11e9-8587-fd1efb2f50dc.png)

This is a neume in 'space 5' (s5).

![CF_15_1_14](https://user-images.githubusercontent.com/23425011/58641065-75076600-82c8-11e9-9d09-7a154aa4bd17.png)

This is a neume in 'space 1' (s1).
